export const data = [
  {
    prodName: 'art-1',
    slug: 'art-1',
    imageUrl: '/images/bijoux_1.jpg',
    isInCart: false,
    count: 0,
  },
  {
    prodName: 'art-2',
    slug: 'art-2',
    imageUrl: '/images/bijoux_2.jpg',
    isInCart: false,
    count: 0,
  },
  {
    prodName: 'art-3',
    slug: 'art-3',
    imageUrl: '/images/bijoux_3.jpg',
    isInCart: false,
    count: 0,
  },
  {
    prodName: 'art-4',
    slug: 'art-4',
    imageUrl: '/images/bijoux_4.jpg',
    isInCart: false,
    count: 0,
  },
  {
    prodName: 'art-5',
    slug: 'art-5',
    imageUrl: '/images/bijoux_5.jpg',
    isInCart: false,
    count: 0,
  },
  {
    prodName: 'art-6',
    slug: 'art-6',
    imageUrl: '/images/bijoux_6.jpg',
    isInCart: false,
    count: 0,
  },
  {
    prodName: 'art-7',
    slug: 'art-7',
    imageUrl: '/images/bijoux_7.jpg',
    isInCart: false,
    count: 0,
  },
  {
    prodName: 'art-8',
    slug: 'art-8',
    imageUrl: '/images/bijoux_8.jpg',
    isInCart: false,
    count: 0,
  },
  {
    prodName: 'art-9',
    slug: 'art-9',
    imageUrl: '/images/bijoux_9.jpg',
    isInCart: false,
    count: 0,
  },
  {
    prodName: 'art-10',
    slug: 'art-10',
    imageUrl: '/images/bijoux_10.jpg',
    isInCart: false,
    count: 0,
  },
  {
    prodName: 'art-12',
    slug: 'art-12',
    imageUrl: '/images/bijoux_12.jpg',
    isInCart: false,
    count: 0,
  },
  {
    prodName: 'art-13',
    slug: 'art-13',
    imageUrl: '/images/bijoux_13.jpg',
    isInCart: false,
    count: 0,
  },
  {
    prodName: 'art-14',
    slug: 'art-14',
    imageUrl: '/images/bijoux_14.jpg',
    isInCart: false,
    count: 0,
  },
  {
    prodName: 'art-15',
    slug: 'art-15',
    imageUrl: '/images/bijoux_15.jpg',
    isInCart: false,
    count: 0,
  },
];
